import {test} from 'vitest';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {geographyCell,geographyReading,geographyAnnualProfile,geographyLongitudeSection} from '../src/physics/geographySampling.ts';
import {geographyKey,geographyBytes,assertGeographyPair,GEOGRAPHY_MASK_ID,GEOGRAPHY_PAYLOAD_SHA,OCEAN_REFERENCE_ID,GEOGRAPHY_SOLVER_ID} from '../src/physics/geographyContract.ts';
import {validateGeographyData} from '../src/physics/geographyData.ts';
import {buildGeographyGrid} from '../src/physics/geographyGrid.ts';
import {GeographyClient} from '../src/ui/geographyClient.ts';
import {decodeGeographyExperiment,encodeGeographyExperiment,geographyExperimentHash,geographyExperimentFromHash,DEFAULT_GEOGRAPHY_EXPERIMENT} from '../src/experiments/geographyExperiment.ts';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const data=JSON.parse(fs.readFileSync(path.join(root,'data/land-fractions.json'),'utf8'));
const config=(tilt=23.44,reference=true)=>({tilt,reference,orbit:{eccentricity:0,perihelion:0,axis:0}});
function solution(c,id=GEOGRAPHY_MASK_ID){const grid=buildGeographyGrid(),N=grid.size;return {tilt:c.tilt,orbit:{...c.orbit},grid,landFraction:id===GEOGRAPHY_MASK_ID?new Float64Array(data.fractions):new Float64Array(N),temperatures:Float64Array.from({length:365*N},(_,k)=>Math.floor(k/N)*.01+(k%N)*.001),years:2,stepsPerDay:2,periodicError:1e-7,energyResidual:1e-6,maxStepEnergyResidual:1e-7,maxRelativeLinearResidual:1e-12,maxLinearIterations:10,minimum:0,maximum:5,provenance:{id,solver:GEOGRAPHY_SOLVER_ID,grid:'phi-midpoint-18x36-v1',payloadSha256:GEOGRAPHY_PAYLOAD_SHA}};}
function pair(c){return {key:geographyKey(c),current:solution(c),reference:c.reference?solution(c,OCEAN_REFERENCE_ID):null};}
class FakeWorker{onmessage=null;onerror=null;onmessageerror=null;terminated=false;requests=[];postMessage(r){this.requests.push(r);}terminate(){this.terminated=true;}ready(p){const r=this.requests[0];this.onmessage?.({data:{id:r.id,key:r.key,kind:'ready',pair:p}});}}
function client(timeout){const workers=[],events=[];const client=new GeographyClient(()=>{const w=new FakeWorker();workers.push(w);return w;},e=>events.push(e),timeout);return {client,workers,events};}

test('native geographic cell, not a fictitious city-resolution interpolation',()=>{const c=geographyCell(25.033,121.5654);assert.equal(c.latitude,25);assert.equal(c.longitude,125);assert.equal(c.row,11);assert.equal(c.column,30);});
test('longitude seam ±180 and full rotations select the same cell',()=>{assert.deepEqual(geographyCell(0,180),geographyCell(0,-180));assert.deepEqual(geographyCell(25,125),geographyCell(25,485));});
test('exact poles have no arbitrary selected longitude',()=>{for(const lat of [-90,90]){const a=geographyCell(lat,-175),b=geographyCell(lat,155);assert.deepEqual(a,b);assert.equal(a.column,null);assert.equal(a.polarMean,true);}});
test('sampling rejects nonfinite location and day',()=>{for(const x of [NaN,Infinity,-Infinity]){assert.throws(()=>geographyCell(x,0));assert.throws(()=>geographyCell(0,x));assert.throws(()=>geographyReading(solution(config()),0,0,x));}assert.throws(()=>geographyCell(91,0));});
test('native cell-centre sampling equals the array value',()=>{const s=solution(config());assert.equal(geographyReading(s,25,125,5).temperature,s.temperatures[4*648+11*36+30]);});
test('fractional model days interpolate only in time',()=>{const s=solution(config()),a=geographyReading(s,25,125,5),b=geographyReading(s,25,125,6),mid=geographyReading(s,25,125,5.5);assert.ok(Math.abs(mid.temperature-(a.temperature+b.temperature)/2)<1e-14);});
test('year seam is periodic and interpolates day365 to day1',()=>{const s=solution(config());assert.equal(geographyReading(s,0,0,366).temperature,geographyReading(s,0,0,1).temperature);assert.equal(geographyReading(s,0,0,-364).temperature,geographyReading(s,0,0,1).temperature);const a=geographyReading(s,0,0,365).temperature,b=geographyReading(s,0,0,1).temperature;assert.equal(geographyReading(s,0,0,365.5).temperature,a+(b-a)*.5);});
test('polar reading is the mean of the adjacent native row',()=>{const s=solution(config());const sum=s.temperatures.subarray(612,648).reduce((a,b)=>a+b,0)/36;assert.equal(geographyReading(s,90,0,1).temperature,sum);});
test('land fraction and effective depth use the same selected cell',()=>{const s=solution(config()),r=geographyReading(s,25,125,172);assert.equal(r.landFraction,s.landFraction[r.cell.index]);assert.equal(r.effectiveDepth,2.5*r.landFraction+50*(1-r.landFraction));});
test('full annual profile samples all365 days without changing longitude',()=>{const s=solution(config()),a=geographyAnnualProfile(s,45,25);assert.equal(a.length,365);for(let d=0;d<365;d++)assert.equal(a[d],geographyReading(s,45,25,d+1).temperature);});
test('atlas is north-first selected-longitude section, not zonal mean',()=>{const s=solution(config()),f=geographyLongitudeSection(s,125);assert.equal(f.length,18*365);assert.equal(f[0],geographyReading(s,85,125,1).temperature);assert.equal(f[17*365+364],geographyReading(s,-85,125,365).temperature);assert.notEqual(f[0],geographyLongitudeSection(s,-125)[0]);});
test('pinned data hash and metadata are verified',async()=>{const m=await validateGeographyData(data);assert.equal(m.provenance.payloadSha256,GEOGRAPHY_PAYLOAD_SHA);assert.equal(m.fractions.length,648);});
test('one altered fraction is rejected instead of silently changing geography',async()=>{const d=structuredClone(data);d.fractions[20]=.123456;await assert.rejects(validateGeographyData(d),/checksum/);});
test('wrong grid or data version cannot be coerced into the pinned dataset',async()=>{for(const [field,value] of [['nlat',36],['firstLatitude',85],['order','north-first']]){const d=structuredClone(data);d.grid[field]=value;await assert.rejects(validateGeographyData(d));}const d=structuredClone(data);d.source.version='4.0.0';await assert.rejects(validateGeographyData(d));});
test('NaN, strings and out-of-range fractions are rejected',async()=>{for(const f of [NaN,Infinity,'1',-1,2]){const d=structuredClone(data);d.fractions[0]=f;await assert.rejects(validateGeographyData(d));}});
test('configuration keys include reference intent and each orbital condition',()=>{const c=config(),key=geographyKey(c);assert.notEqual(key,geographyKey({...c,reference:false}));assert.notEqual(key,geographyKey({...c,tilt:60}));for(const k of ['eccentricity','perihelion','axis'])assert.notEqual(key,geographyKey({...c,orbit:{...c.orbit,[k]:k==='eccentricity'?.1:20}}));});
test('invalid configurations fail before they invalidate a current request',()=>{const {client:c,workers,events}=client();c.request(config());assert.throws(()=>c.request(config(NaN)));assert.equal(workers[0].terminated,false);assert.equal(events.length,1);c.dispose();});
test('new conditions terminate the old worker and late replies are ignored',()=>{const {client:c,workers,events}=client();const a=config(),b=config(60);c.request(a);const old=workers[0].onmessage,req=workers[0].requests[0];c.request(b);assert.equal(workers[0].terminated,true);old({data:{id:req.id,key:req.key,kind:'ready',pair:pair(a)}});assert.equal(events.filter(e=>e.kind==='ready').length,0);workers[1].ready(pair(b));assert.equal(events.at(-1).kind,'ready');assert.equal(events.at(-1).pair.current.tilt,60);c.dispose();});
test('same pending conditions do not launch duplicate work',()=>{const {client:c,workers}=client();c.request(config());c.request(config());assert.equal(workers.length,1);c.dispose();});
test('request configuration snapshots survive caller mutation',()=>{const {client:c,workers}=client(),v=config();c.request(v);v.tilt=90;v.orbit.axis=100;assert.equal(workers[0].requests[0].configuration.tilt,23.44);assert.equal(workers[0].requests[0].configuration.orbit.axis,0);c.dispose();});
test('completed fields are reused from the bounded cache',()=>{const {client:c,workers,events}=client(),v=config();c.request(v);workers[0].ready(pair(v));c.request(v);assert.equal(workers.length,1);assert.equal(events.at(-1).cached,true);c.dispose();});
test('LRU remains at most2 pairs and8MiB; discarded condition recomputes',()=>{const {client:c,workers}=client();for(const tilt of [10,20,30]){const v=config(tilt);c.request(v);workers.at(-1).ready(pair(v));}assert.equal(c.cachedEntries,2);assert.ok(c.cachedBytes<=8*1024*1024);c.request(config(10));assert.equal(workers.length,4);c.dispose();});
test('successful final reply cannot be followed by another terminal event',()=>{const {client:c,workers,events}=client(),v=config();c.request(v);const callback=workers[0].onmessage,r=workers[0].requests[0];workers[0].ready(pair(v));callback({data:{id:r.id,key:r.key,kind:'error',message:'late'}});assert.equal(events.at(-1).kind,'ready');c.dispose();});
test('cancel disposes active work and excludes late data',()=>{const {client:c,workers,events}=client(),v=config();c.request(v);const callback=workers[0].onmessage,r=workers[0].requests[0];c.cancel();callback({data:{id:r.id,key:r.key,kind:'ready',pair:pair(v)}});assert.equal(events.at(-1).kind,'cancelled');assert.equal(workers[0].terminated,true);c.dispose();});
test('timeout explicitly fails and a fresh retry can run',async()=>{const {client:c,workers,events}=client(15),v=config();c.request(v);await new Promise(r=>setTimeout(r,30));assert.equal(events.at(-1).kind,'error');assert.match(events.at(-1).message,/timed out/);assert.equal(workers[0].terminated,true);c.request(v);workers[1].ready(pair(v));assert.equal(events.at(-1).kind,'ready');c.dispose();});
test('worker errors never substitute Classic or old results',()=>{const {client:c,workers,events}=client();c.request(config());workers[0].onerror({message:'GPU-independent worker failure',preventDefault(){}});assert.equal(events.at(-1).kind,'error');assert.equal(c.cachedEntries,0);c.dispose();});
test('wrong mask, solver or tilt is rejected before a result becomes visible',()=>{for(const mutate of [s=>s.tilt=77,s=>s.provenance.id='wrong',s=>s.provenance.solver='future',s=>s.provenance.payloadSha256='wrong']){const c=config(),p=pair(c);mutate(p.current);assert.throws(()=>assertGeographyPair(p,c));}});
test('nonfinite or unconverged fields fail validation',()=>{for(const mutate of [s=>s.temperatures[100]=NaN,s=>s.periodicError=.01,s=>s.maxStepEnergyResidual=.001,s=>s.landFraction[4]=-1]){const c=config(),p=pair(c);mutate(p.current);assert.throws(()=>assertGeographyPair(p,c));}});
test('dispose drops all retained results and blocks later requests',()=>{const {client:c,workers}=client(),v=config();c.request(v);workers[0].ready(pair(v));assert.ok(c.cachedBytes>0);c.dispose();assert.equal(c.cachedBytes,0);assert.throws(()=>c.request(v));});
test('byte accounting includes both fields and their metadata',()=>{const p=pair(config());assert.ok(geographyBytes(p)>2*365*648*8);assert.ok(geographyBytes(p)<4*1024*1024);});
test('geography JSON and URL round trips retain the exact requested condition',()=>{const s={...structuredClone(DEFAULT_GEOGRAPHY_EXPERIMENT),tilt:60,longitude:-180,day:365.5};assert.deepEqual(decodeGeographyExperiment(encodeGeographyExperiment(s)),s);assert.deepEqual(geographyExperimentFromHash(geographyExperimentHash(s)),s);});
test('Earth schema3 is not silently interpreted as geography settings',()=>{assert.throws(()=>decodeGeographyExperiment(JSON.stringify({application:'earth-axial-tilt',version:3,state:DEFAULT_GEOGRAPHY_EXPERIMENT})));assert.equal(geographyExperimentFromHash('#lab=3'),null);});
test('invalid settings never produce a partly accepted experiment',()=>{const base=JSON.parse(encodeGeographyExperiment(DEFAULT_GEOGRAPHY_EXPERIMENT));for(const field of ['day','latitude','longitude']){const v=structuredClone(base);v.state[field]=999;assert.throws(()=>decodeGeographyExperiment(JSON.stringify(v)));}for(const change of [v=>v.version=2,v=>v.mask='future',v=>v.state.layer='unknown',v=>{v.state.reference=false;v.state.layer='difference';}]){const v=structuredClone(base);change(v);assert.throws(()=>decodeGeographyExperiment(JSON.stringify(v)));}});
test('size bounds and malicious markup are not silently accepted as values',()=>{assert.throws(()=>decodeGeographyExperiment(' '.repeat(4097)));assert.throws(()=>geographyExperimentFromHash('#geo=%ZZ'));const v=JSON.parse(encodeGeographyExperiment(DEFAULT_GEOGRAPHY_EXPERIMENT));v.state.latitude='<script>';assert.throws(()=>decodeGeographyExperiment(JSON.stringify(v)));});
